#!/usr/bin/env python3
"""
Generate self-signed SSL certificate for ESP32 HTTPS server
Outputs certificate and private key as C header file
"""

from cryptography import x509
from cryptography.x509.oid import NameOID
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization
import datetime

# Generate private key
print("Generating RSA private key...")
private_key = rsa.generate_private_key(
    public_exponent=65537,
    key_size=2048,
)

# Create certificate
print("Creating self-signed certificate...")
subject = issuer = x509.Name([
    x509.NameAttribute(NameOID.COUNTRY_NAME, u"US"),
    x509.NameAttribute(NameOID.STATE_OR_PROVINCE_NAME, u"CA"),
    x509.NameAttribute(NameOID.LOCALITY_NAME, u"Local"),
    x509.NameAttribute(NameOID.ORGANIZATION_NAME, u"PawTracker"),
    x509.NameAttribute(NameOID.COMMON_NAME, u"pawtracker.local"),
])

cert = x509.CertificateBuilder().subject_name(
    subject
).issuer_name(
    issuer
).public_key(
    private_key.public_key()
).serial_number(
    x509.random_serial_number()
).not_valid_before(
    datetime.datetime.utcnow()
).not_valid_after(
    datetime.datetime.utcnow() + datetime.timedelta(days=3650)  # 10 years
).add_extension(
    x509.SubjectAlternativeName([
        x509.DNSName(u"pawtracker.local"),
        x509.DNSName(u"localhost"),
    ]),
    critical=False,
).sign(private_key, hashes.SHA256())

# Serialize to PEM format
cert_pem = cert.public_bytes(serialization.Encoding.PEM).decode('utf-8')
key_pem = private_key.private_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PrivateFormat.TraditionalOpenSSL,
    encryption_algorithm=serialization.NoEncryption()
).decode('utf-8')

# Convert to C header format
def to_c_array(pem_string, var_name):
    lines = pem_string.strip().split('\n')
    c_code = f'const char {var_name}[] PROGMEM = R"EOF(\n'
    for line in lines:
        c_code += line + '\n'
    c_code += ')EOF";\n'
    return c_code

# Generate header file
header_content = """// Auto-generated SSL certificate and private key
// Valid for 10 years from generation date
// Generated by generate_cert.py

#ifndef SSL_CERT_H
#define SSL_CERT_H

"""

header_content += to_c_array(cert_pem, "serverCert")
header_content += "\n"
header_content += to_c_array(key_pem, "serverKey")

header_content += """
#endif // SSL_CERT_H
"""

# Write to file
output_file = "src/ssl_cert.h"
with open(output_file, 'w') as f:
    f.write(header_content)

print(f"\n✓ Certificate and key generated successfully!")
print(f"✓ Output written to: {output_file}")
print(f"\nCertificate valid for 10 years")
print(f"Common Name: pawtracker.local")
print(f"\nNote: Browsers will show a security warning for self-signed certificates.")
print(f"      You'll need to accept the certificate to proceed.")
